// Root
export const INIT_STORE = 'INIT_STORE'

// Theme
export const CHANGE_THEME = 'CHANGE_THEME'

// Body
export const LOGIN_URLS_REQUEST = 'LOGIN_URLS_REQUEST'
export const LOGIN_URLS_SUCCESS = 'LOGIN_URLS_SUCCESS'
export const LOGIN_URLS_FAILURE = 'LOGIN_URLS_FAILURE'
export const USER_ACCOUNT_REQUEST = 'USER_ACCOUNT_REQUEST'
export const USER_ACCOUNT_SUCCESS = 'USER_ACCOUNT_SUCCESS'
export const USER_ACCOUNT_FAILURE = 'USER_ACCOUNT_FAILURE'
export const ACCOUNTS_REQUEST = 'ACCOUNTS_REQUEST'
export const ACCOUNTS_SUCCESS = 'ACCOUNTS_SUCCESS'
export const ACCOUNTS_FAILURE = 'ACCOUNTS_FAILURE'
export const USERS_REQUEST = 'USERS_REQUEST'
export const USERS_SUCCESS = 'USERS_SUCCESS'
export const USERS_FAILURE = 'USERS_FAILURE'
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE'
export const TOGGLE_LOGIN_STATUS = 'TOGGLE_LOGIN_STATUS'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const TOGGLE_FETCHING = 'TOGGLE_FETCHING'

//Demands
export const DEMANDS_REQUEST = 'DEMANDS_REQUEST'
export const DEMANDS_SUCCESS = 'DEMANDS_SUCCESS'
export const DEMANDS_FAILURE = 'DEMANDS_FAILURE'

// toDos
export const ADD_NEW_TODO = 'ADD_NEW_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const SAVE_TODO = 'SAVE_TODO'
