// Root
export const INIT_STORE = 'INIT_STORE'

// Theme
export const CHANGE_THEME = 'CHANGE_THEME'

// Body
export const REQUEST_LOGIN_URLS = 'REQUEST_LOGIN_URLS'
export const REQUEST_ACCOUNT_DATA = 'REQUEST_ACCOUNT_DATA'
export const REQUEST_USERS_DATA = 'REQUEST_USERS_DATA'
export const RECEIVE_LOGIN_URLS_SUCCESS = 'RECEIVE_LOGIN_URLS_SUCCESS'
export const RECEIVE_ACCOUNT_DATA_SUCCESS = 'RECEIVE_ACCOUNT_DATA_SUCCESS'
export const RECEIVE_USERS_DATA_SUCCESS = 'RECEIVE_USERS_DATA_SUCCESS'
export const RECEIVE_LOGIN_URLS_ERROR = 'RECEIVE_LOGIN_URLS_ERROR'
export const RECEIVE_ACCOUNT_DATA_ERROR = 'RECEIVE_ACCOUNT_DATA_ERROR'
export const RECEIVE_USERS_DATA_ERROR = 'RECEIVE_USERS_DATA_ERROR'
export const TOGGLE_LOGIN_STATUS = 'TOGGLE_LOGIN_STATUS'
export const TOGGLE_DRAWER = 'TOGGLE_DRAWER'
export const TOGGLE_FETCHING = 'TOGGLE_FETCHING'

// toDos
export const ADD_NEW_TODO = 'ADD_NEW_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const REMOVE_TODO = 'REMOVE_TODO'
export const SAVE_TODO = 'SAVE_TODO'
